## Introduction to the GPT family

In [1]:
from transformers import pipeline, set_seed, GPT2Tokenizer, GPT2LMHeadModel
from torch import tensor, numel
from bertviz import model_view

set_seed(42)

In [2]:
# pipeline object in transformers provides easy access to transformer usage
generator = pipeline('text-generation', model='gpt2')

# finish the sentence
generator("Hello, I'm a language model and I", max_length=30, num_return_sequences=3)

Downloading:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "Hello, I'm a language model and I don't want to be a computer programmer. As for all those bad languages in JavaScript, I'll never"},
 {'generated_text': "Hello, I'm a language model and I know that's not the right language to build this program of yours. What was wrong with the code?"},
 {'generated_text': "Hello, I'm a language model and I'm trying to work with that much of this, and have this kind of a great conversation about language model"}]

In [3]:
# load up a tokenizer
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

'sinan' in tokenizer.get_vocab()

False

In [4]:
# encode a string and then convert the ids back into tokens. Note the Ġ character denoting a space before the token
tokenizer.convert_ids_to_tokens(tokenizer.encode('Sinan loves a beautiful day'))

['Sin', 'an', 'Ġloves', 'Ġa', 'Ġbeautiful', 'Ġday']

In [5]:
tokenizer.encode('Sinan loves a beautiful day')  # ids

[46200, 272, 10408, 257, 4950, 1110]

In [6]:
encoded = tokenizer.encode('Sinan loves a beautiful day', return_tensors='pt')  # as a pytorch tensor

encoded

tensor([[46200,   272, 10408,   257,  4950,  1110]])

In [7]:
# load up a tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2')

In [8]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [9]:
encoded

tensor([[46200,   272, 10408,   257,  4950,  1110]])

In [10]:
model.transformer.wte(encoded).shape  # 1 item in batch x 6 tokens x token dimension

torch.Size([1, 6, 768])

In [11]:
model.transformer.wpe(tensor([0, 1, 2, 3, 4, 5]).reshape(1, 6)).shape  # manually create position vectors

torch.Size([1, 6, 768])

In [12]:
# create GPT input
initial_input = model.transformer.wte(encoded) + model.transformer.wpe(tensor([0, 1, 2, 3, 4, 5]).reshape(1, 6))

initial_input.shape

torch.Size([1, 6, 768])

In [13]:
initial_input = model.transformer.drop(initial_input)  # run our input through the model's initual dropout later
initial_input

tensor([[[ 0.0107, -0.2453,  0.1275,  ..., -0.1969,  0.0006,  0.1539],
         [-0.1013, -0.0894, -0.0378,  ..., -0.0534, -0.0527,  0.0046],
         [-0.0716, -0.1690,  0.0386,  ..., -0.2034, -0.0197, -0.1113],
         [-0.0509, -0.0682,  0.1526,  ...,  0.0527,  0.0912, -0.0455],
         [ 0.0612,  0.1425,  0.1402,  ...,  0.0964,  0.0510,  0.1474],
         [-0.1283, -0.0632,  0.1287,  ..., -0.0907, -0.0655,  0.1085]]],
       grad_fn=<AddBackward0>)

In [14]:
model.lm_head

Linear(in_features=768, out_features=50257, bias=False)

In [15]:
for module in model.transformer.h:  # run the initial_input through every decoder in the stack
    initial_input = module(initial_input)[0]
    
initial_input = model.transformer.ln_f(initial_input)  # and then the final layer norm

In [16]:
initial_input

tensor([[[ 0.0542, -0.0179, -0.3388,  ..., -0.0948, -0.1067,  0.0129],
         [-0.4805,  0.1008, -0.7313,  ...,  0.0471, -0.4113,  0.0902],
         [ 0.0344, -0.2259, -0.5293,  ..., -0.1202,  0.1355,  0.2287],
         [-0.2374,  0.1787,  0.1845,  ..., -0.4057, -0.3617, -0.1861],
         [ 0.0235,  0.1212, -1.0182,  ..., -0.0597,  0.0020, -0.2220],
         [ 0.1206, -0.5034, -1.5260,  ..., -0.3367, -0.2821, -0.0410]]],
       grad_fn=<NativeLayerNormBackward0>)

In [17]:
# same as just running through the model
(initial_input == model(encoded, output_hidden_states=True).hidden_states[-1]).all()

tensor(True)

In [18]:
total_params = 0
for param in model.parameters():
    total_params += numel(param)
    
print(f'Number of params: {total_params:,}')

Number of params: 124,439,808


## Masked multi-headed attention

In [19]:
import torch
import pandas as pd


In [20]:
phrase = 'My friend was right about this class. It is so fun!'
encoded_phrase = tokenizer(phrase, return_tensors='pt')

response = model(**encoded_phrase, output_attentions=True, output_hidden_states=True)

len(response.attentions)

12

In [21]:
encoded_phrase

{'input_ids': tensor([[3666, 1545,  373,  826,  546,  428, 1398,   13,  632,  318,  523, 1257,
            0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [22]:
response.attentions[-1].shape  # represtnations from the final decoder

torch.Size([1, 12, 13, 13])

In [23]:
encoded_phrase['input_ids'].shape

torch.Size([1, 13])

In [24]:
tokens = tokenizer.convert_ids_to_tokens(encoded_phrase['input_ids'][0])

tokens

['My',
 'Ġfriend',
 'Ġwas',
 'Ġright',
 'Ġabout',
 'Ġthis',
 'Ġclass',
 '.',
 'ĠIt',
 'Ġis',
 'Ġso',
 'Ġfun',
 '!']

In [25]:
# Layer index 9, head 0. Check out the almost 60% attention the token it is giving to the token class
arr = response.attentions[9][0][0]

n_digits = 3

attention_df = pd.DataFrame((torch.round(arr * 10**n_digits) / (10**n_digits)).detach()).applymap(float)

attention_df.columns = tokens
attention_df.index = tokens

attention_df


My  Ġfriend   Ġwas  Ġright  Ġabout  Ġthis  Ġclass      .    ĠIt  \
My       1.000    0.000  0.000   0.000   0.000  0.000   0.000  0.000  0.000   
Ġfriend  0.968    0.032  0.000   0.000   0.000  0.000   0.000  0.000  0.000   
Ġwas     0.824    0.145  0.031   0.000   0.000  0.000   0.000  0.000  0.000   
Ġright   0.979    0.008  0.007   0.005   0.000  0.000   0.000  0.000  0.000   
Ġabout   0.979    0.008  0.004   0.005   0.005  0.000   0.000  0.000  0.000   
Ġthis    0.924    0.031  0.007   0.006   0.016  0.016   0.000  0.000  0.000   
Ġclass   0.946    0.005  0.001   0.001   0.001  0.002   0.044  0.000  0.000   
.        0.691    0.013  0.003   0.003   0.002  0.006   0.269  0.013  0.000   
ĠIt      0.318    0.003  0.003   0.003   0.006  0.018   0.599  0.018  0.032   
Ġis      0.331    0.006  0.002   0.002   0.003  0.018   0.533  0.013  0.062   
Ġso      0.141    0.010  0.005   0.004   0.004  0.026   0.645  0.023  0.096   
Ġfun     0.532    0.015  0.003   0.002   0.001  0.002   0.317  0.029  0.035   
!        0.527    0.008  0.003   0.001   0.001  0.003   0.245  0.026  0.034   

           Ġis    Ġso   Ġfun      !  
My       0.000  0.000  0.000  0.000  
Ġfriend  0.000  0.000  0.000  0.000  
Ġwas     0.000  0.000  0.000  0.000  
Ġright   0.000  0.000  0.000  0.000  
Ġabout   0.000  0.000  0.000  0.000  
Ġthis    0.000  0.000  0.000  0.000  
Ġclass   0.000  0.000  0.000  0.000  
.        0.000  0.000  0.000  0.000  
ĠIt      0.000  0.000  0.000  0.000  
Ġis      0.030  0.000  0.000  0.000  
Ġso      0.041  0.003  0.000  0.000  
Ġfun     0.014  0.003  0.047  0.000  
!        0.012  0.007  0.046  0.089

In [26]:
tokens = tokenizer.convert_ids_to_tokens(encoded_phrase['input_ids'][0]) 
model_view(response.attentions, tokens)

<IPython.core.display.Javascript object>

In [27]:
response.hidden_states[-1].shape

torch.Size([1, 13, 768])

In [28]:
response.logits

tensor([[[ -33.0735,  -32.3349,  -35.2379,  ...,  -38.3576,  -38.4758,
           -33.0943],
         [ -98.8075,  -98.9729, -105.2267,  ..., -109.0421, -104.7381,
          -101.0802],
         [-131.2764, -130.8178, -135.2054,  ..., -138.3585, -134.9846,
          -134.1658],
         ...,
         [-120.6479, -122.7568, -127.1870,  ..., -130.4343, -129.5815,
          -125.1274],
         [ -73.8157,  -78.6168,  -85.3995,  ...,  -91.8287,  -91.7846,
           -81.4570],
         [-134.7545, -134.9494, -136.2912,  ..., -147.1822, -148.1732,
          -130.7045]]], grad_fn=<UnsafeViewBackward0>)

In [29]:
response.logits.shape

torch.Size([1, 13, 50257])

In [30]:
# look at the top next token in the auto-regressive language modelling task
pd.DataFrame(
    zip(tokens, tokenizer.convert_ids_to_tokens(response.logits.argmax(2)[0])), 
    columns=['Sequence up until', 'Next token with highest probability']
)

Sequence up until Next token with highest probability
0                 My                                   Ċ
1            Ġfriend                                   ,
2               Ġwas                                  Ġa
3             Ġright                                   .
4             Ġabout                               Ġthat
5              Ġthis                                   .
6             Ġclass                                   .
7                  .                                  ĠI
8                ĠIt                                  's
9                Ġis                                  Ġa
10               Ġso                          Ġimportant
11              Ġfun                                 Ġto
12                 !                                  ĠI

In [31]:
generator('My friend was right', max_length=4, num_return_sequences=5)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Input length of input_ids is 4, but `max_length` is set to 4. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.


[{'generated_text': 'My friend was right and'},
 {'generated_text': 'My friend was right.'},
 {'generated_text': 'My friend was right about'},
 {'generated_text': 'My friend was right,'},
 {'generated_text': 'My friend was right,"'}]

In [32]:
generator(phrase, max_length=20, num_return_sequences=1, do_sample=False)  # greedy search

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'My friend was right about this class. It is so fun! I love it! I love the'}]

In [33]:
generator(phrase, max_length=20, num_return_sequences=1, do_sample=True)  # greedy search with sampling

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'My friend was right about this class. It is so fun! Soooo hot as fuck. The'}]

## Pre-training GPT

In [34]:
from transformers import pipeline, set_seed
from torch import tensor

generator = pipeline('text-generation', model='gpt2', tokenizer=tokenizer)
set_seed(0)

In [35]:
# Bias
generator("The holocaust was", max_length=10, num_return_sequences=10, temperature=0.8, beams=2)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/folders/y9/9xqbqkg90tnc0cmm0dxt985m0000gn/T/ipykernel_95019/1556950989.py:2 in <module>     │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/var/folders/y9/9xqbqkg90tnc0cmm0dxt985m0000gn/T/ipykernel_95019/1556950989.py'                 │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/text_generation.py:187 in      │
│ __call__                                                                                         │
│                                                                                                  │
│   184 │   │   │   - **generated_token_ids** (`torch.Tensor` or `tf.Tensor`, present when `retu   │
│   185 │   │   │     ids of the generated text.                                                   │
│   186 │   │   """                                                                                │
│ ❱ 187 │   │   return super().__call__(text_inputs, **kwargs)                                     │
│   188 │                                                                                          │
│   189 │   def preprocess(self, prompt_text, prefix="", handle_long_generation=None, **generate   │
│   190 │   │   inputs = self.tokenizer(                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/base.py:1074 in __call__       │
│                                                                                                  │
│   1071 │   │   elif is_iterable:                                                                 │
│   1072 │   │   │   return self.iterate(inputs, preprocess_params, forward_params, postprocess_p  │
│   1073 │   │   else:                                                                             │
│ ❱ 1074 │   │   │   return self.run_single(inputs, preprocess_params, forward_params, postproces  │
│   1075 │                                                                                         │
│   1076 │   def run_multi(self, inputs, preprocess_params, forward_params, postprocess_params):   │
│   1077 │   │   return [self.run_single(item, preprocess_params, forward_params, postprocess_par  │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/base.py:1081 in run_single     │
│                                                                                                  │
│   1078 │                                                                                         │
│   1079 │   def run_single(self, inputs, preprocess_params, forward_params, postprocess_params):  │
│   1080 │   │   model_inputs = self.preprocess(inputs, **preprocess_params)                       │
│ ❱ 1081 │   │   model_outputs = self.forward(model_inputs, **forward_params)                      │
│   1082 │   │   outputs = self.postprocess(model_outputs, **postprocess_params)                   │
│   1083 │   │   return outputs                                                                    │
│   1084                                                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/base.py:990 in forward         │
│                                                                                                  │
│    987 │   │   │   │   inference_context = self.get_inferen

In [ ]:
generator("Jewish people are", max_length=10, num_return_sequences=10, temperature=0.8, beams=2)

In [ ]:
generator("Christian people are", max_length=10, num_return_sequences=10, temperature=0.8, beams=2)

In [ ]:
generator("The earth is", max_length=10, num_return_sequences=10, temperature=0.8, beams=2)

## Few-shot learning

In [ ]:
print(generator("""Sentiment Analysis
Text: I hate it when my phone battery dies.
Sentiment: Negative
###
Text: My day has been really great!
Sentiment: Positive
###
Text: Not a fan when it is cloudy
Sentiment:""", top_k=2, temperature=0.1, max_length=55)[0]['generated_text'])

In [ ]:
print(generator("""Question/Answering
C: Google was founded in 1998 by Larry Page and Sergey Brin while they were Ph.D. students at Stanford University in California. Together they own about 14 percent of its shares and control 56 percent of the stockholder voting power through supervoting stock.
Q: When was Google founded?
A: 1998
###
C: Hugging Face is a company which develops social AI-run chatbot applications. It was established in 2016 by Clement Delangue and Julien Chaumond. The company is based in Brooklyn, New York, United States.
Q: What does Hugging Face develop?
A: social AI-run chatbot applications
###
C: The New York Jets are a professional American football team based in the New York metropolitan area. The Jets compete in the National Football League (NFL) as a member club of the league's American Football Conference (AFC) East division.
Q: What division do the Jets play in?
A:""", top_k=5, beams=2, max_length=215, temperature=0.5)[0]['generated_text'])


In [ ]:
## Zero Shot Learning

In [ ]:
# Same question as before, with no previous examples ie Zero-shot learning. Hit or miss
print(generator(
    '''Question/Answering
C: The New York Jets are a professional American football team based in the New York metropolitan area. The Jets compete in the National Football League (NFL) as a member club of the league's American Football Conference (AFC) East division.
Q: What division do the Jets play in?
A:''',
    top_k=5, beams=2, max_length=80, temperature=0.5)[0]['generated_text']
)

In [ ]:
# Zero-shot doesn't work as much with the sentiment analysis example
print(generator("""Sentiment Analysis
Text: This new music video was so good
Sentiment:""", top_k=2, temperature=0.1, max_length=55)[0]['generated_text'])

In [ ]:
# Zero-shot abstractive summarization

In [ ]:
to_summarize = """This training will focus on how the GPT family of models are used for NLP tasks including abstractive text summarization and natural language generation. The training will begin with an introduction to necessary concepts including masked self attention, language models, and transformers and then build on those concepts to introduce the GPT architecture. We will then move into how GPT is used for multiple natural language processing tasks with hands-on examples of using pre-trained GPT-2 models as well as fine-tuning these models on custom corpora.

GPT models are some of the most relevant NLP architectures today and it is closely related to other important NLP deep learning models like BERT. Both of these models are derived from the newly invented transformer architecture and represent an inflection point in how machines process language and context.

The Natural Language Processing with Next-Generation Transformer Architectures series of online trainings provides a comprehensive overview of state-of-the-art natural language processing (NLP) models including GPT and BERT which are derived from the modern attention-driven transformer architecture and the applications these models are used to solve today. All of the trainings in the series blend theory and application through the combination of visual mathematical explanations, straightforward applicable Python examples within hands-on Jupyter notebook demos, and comprehensive case studies featuring modern problems solvable by NLP models. (Note that at any given time, only a subset of these classes will be scheduled and open for registration.)"""

In [ ]:
print(generator(
    f"""Summarization Task:\n{to_summarize}\nTL;DR:""", 
    max_length=400, beams=5, temperature=0.7
)[0]['generated_text'].split('TL;DR:')[1])
